//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASMUL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cable_por_entrega
    {
        public int id_cablePorEntrega { get; set; }
        public int id_entrega { get; set; }
        public int id_cable { get; set; }
    
        public virtual cable cable { get; set; }
        public virtual entrega entrega { get; set; }
    }
}
