//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASMUL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public int id_configuracion { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public string observacion { get; set; }
    }
}
