//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASMUL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public entrega()
        {
            this.cable_por_entrega = new HashSet<cable_por_entrega>();
            this.entrega_detalle = new HashSet<entrega_detalle>();
        }
    
        public int id_entrega { get; set; }
        public string nro_entrega { get; set; }
        public System.DateTime fecha_transaccion { get; set; }
        public int id_finca { get; set; }
        public bool confirmado { get; set; }
        public string solicitante { get; set; }
        public int semana { get; set; }
        public int periodo { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cable_por_entrega> cable_por_entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrega_detalle> entrega_detalle { get; set; }
    }
}
