//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASMUL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrega
    {
        public int id_entrega { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public Nullable<int> id_finca { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> id_cable { get; set; }
        public Nullable<int> id_stock { get; set; }
        public Nullable<int> cant_solicitada { get; set; }
        public Nullable<int> cant_entregada { get; set; }
        public Nullable<int> semana { get; set; }
        public Nullable<int> periodo { get; set; }
    
        public virtual item item { get; set; }
        public virtual finca finca { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual cable cable { get; set; }
    }
}
