//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASMUL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.entrega_detalle = new HashSet<entrega_detalle>();
            this.mercaderia_detalle = new HashSet<mercaderia_detalle>();
            this.movimiento_detalle = new HashSet<movimiento_detalle>();
            this.pedido_detalle = new HashSet<pedido_detalle>();
            this.requisa_detalle = new HashSet<requisa_detalle>();
        }
    
        public int id_item { get; set; }
        public string cod_item { get; set; }
        public int id_categoria { get; set; }
        public int id_unidad_medida { get; set; }
        public string descripcion { get; set; }
        public int cant_disponible { get; set; }
        public bool activo { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrega_detalle> entrega_detalle { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mercaderia_detalle> mercaderia_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_detalle> movimiento_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_detalle> pedido_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisa_detalle> requisa_detalle { get; set; }
    }
}
