//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASMUL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercaderia_recibida
    {
        public int id_mercaderia_recibida { get; set; }
        public string nro_mercaderia { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
        public Nullable<int> cant_recibida { get; set; }
        public Nullable<int> semana { get; set; }
        public Nullable<int> periodo { get; set; }
    
        public virtual solicitud_pedido solicitud_pedido { get; set; }
    }
}
