//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASMUL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud_pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solicitud_pedido()
        {
            this.mercaderia_recibida = new HashSet<mercaderia_recibida>();
        }
    
        public int id_solicitud_pedido { get; set; }
        public string nro_pedido { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public Nullable<int> id_finca { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
        public Nullable<int> cant_solicitada { get; set; }
        public Nullable<int> semana { get; set; }
        public Nullable<int> periodo { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual finca finca { get; set; }
        public virtual item item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mercaderia_recibida> mercaderia_recibida { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
    }
}
